# Generated by Django 4.0.6 on 2022-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
