# Generated by Django 4.0.6 on 2022-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_flower_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
